language: ruby
bundler_args: --without development production
rvm:
  - 1.9.3
script: bundle exec rspec spec

before_script:
  - cp config/database_ci.yml config/database.yml
  - psql -c 'create database recipes_test;' -U postgres
