language: ruby
bundler_args: --without development production
rvm:
  - 1.9.3
script:
  - WITHOUT_VCR=1 bundle exec rspec spec --format documentation
  - WITHOUT_VCR=1 bundle exec spinach

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - cp config/database_ci.yml config/database.yml
  - psql -c 'create database recipes_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:reset
